# This is a basic workflow to help you get started with Actions

name: Esteira de Ambientes


on:

  pull_request:
    types: [labeled]
  push:
    branches: Desenvolvimento
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  build:
    if: contains(github.event.label.name, 'deploy Desenvolvimento')
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-Desenvolvimento:
    runs-on: ubuntu-latest
    environment:
      name: Desenvolvimento
      url: ferhmdiogo@gmail.com
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Develop!
        
  deploy-Homologacao:
    runs-on: ubuntu-latest
    environment:
      name: Homologacao
      url: ferhmdiogo@gmail.com
    needs: deploy-Desenvolvimento
    steps:
      - name: Run a one-line script
        run: echo Deploy Homolog!
        
  deploy-main:
    runs-on: ubuntu-latest
    environment:
      name: main
      url: ferhmdiogo@gmail.com
    needs: deploy-Homologacao
    steps:
      - name: Run a one-line script
        run: echo Deploy Prod!     
