# This is a basic workflow to help you get started with Actions

name: Esteira de Ambientes


on:

  pull_request:
    types: [labeled]
  push:
    branches: Desenvolvimento
jobs:
  build:
    if: contains(github.event.label.name, 'deploy Desenvolvimento')
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-Desenvolvimento:
    runs-on: self-hosted
    environment:
      name: Desenvolvimento
      url: ferhmdiogo@gmail.com
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Develop!
        
  deploy-Homologacao:
    runs-on: self-hosted
    environment:
      name: Homologacao
      url: ferhmdiogo@gmail.com
    needs: deploy-Desenvolvimento
    steps:
      - name: Run a one-line script
        run: echo Deploy Homolog!
        
  deploy-main:
    runs-on: self-hosted
    environment:
      name: main
      url: ferhmdiogo@gmail.com
    needs: deploy-Homologacao
    steps:
      - name: Run a one-line script
        run: echo Deploy Prod!     
